package presentacion;

public class ejemplo extends javax.swing.JFrame {

    public ejemplo() {
        Barcos();

    }
    public static int[][] coordenada = new int[10][10];
    //matriz
    public void Barcos() {
        for (int i = 0; i < 9; i++) {
           //USAS EL DE RANDOM PAARA FILA Y COLUMNA
           //FILA= fil 
           //COLUMNA= col
           //USAS RANDOM. 
            System.out.println("f " + fil);
            System.out.println("c " + col);
            usuario1[col][fil] = 1;
        }
        usuario1[0][0] = 1;
        imprimirUsuario1();
    }

    public void imprimir() // funcion para imprimir las filas y columnas
    {
        System.out.println("\n\n");
        for (int fila = 0; fila < 10; fila++) //ciclo para las filas 
        {
            System.out.println("");//salto de linea 
            for (int col = 0; col < 10; col++) //ciclo para las columnas 
            {
                System.out.print("\t" + coordenada[fila][col]);
            }
        }
    }

    public void imprimirUsuario1() // funcion para imprimir las filas y columnas
    {
        System.out.println("\n\n");
        for (int fila = 0; fila < 10; fila++) //ciclo para las filas 
        {
            System.out.println("");//salto de linea 
            for (int col = 0; col < 10; col++) //ciclo para las columnas 
            {
                System.out.print("\t" + usuario1[fila][col]);

            }
        }
    }

    public boolean comparar(int data_c, int data_f) {
        for (int fila = 0; fila < 10; fila++) {
            for (int col = 0; col < 10; col++) {
                if (1 == usuario1[data_c][data_f]) {
                }
            }
        }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        bo00 = new javax.swing.JButton();
        bo01 = new javax.swing.JButton();
        bo02 = new javax.swing.JButton();
        bo03 = new javax.swing.JButton();
        bo04 = new javax.swing.JButton();
        bo05 = new javax.swing.JButton();
        bo06 = new javax.swing.JButton();
        bo07 = new javax.swing.JButton();
        bo08 = new javax.swing.JButton();
        bo09 = new javax.swing.JButton();
        bo10 = new javax.swing.JButton();
        bo11 = new javax.swing.JButton();
        bo12 = new javax.swing.JButton();
        bo13 = new javax.swing.JButton();
        bo14 = new javax.swing.JButton();
        bo15 = new javax.swing.JButton();
        bo16 = new javax.swing.JButton();
        bo17 = new javax.swing.JButton();
        bo18 = new javax.swing.JButton();
        bo19 = new javax.swing.JButton();
        bo20 = new javax.swing.JButton();
        bo21 = new javax.swing.JButton();
        bo22 = new javax.swing.JButton();
        bo23 = new javax.swing.JButton();
        bo24 = new javax.swing.JButton();
        bo25 = new javax.swing.JButton();
        bo26 = new javax.swing.JButton();
        bo27 = new javax.swing.JButton();
        bo28 = new javax.swing.JButton();
        bo29 = new javax.swing.JButton();
        bo30 = new javax.swing.JButton();
        bo31 = new javax.swing.JButton();
        bo32 = new javax.swing.JButton();
        bo33 = new javax.swing.JButton();
        bo34 = new javax.swing.JButton();
        bo35 = new javax.swing.JButton();
        bo36 = new javax.swing.JButton();
        bo37 = new javax.swing.JButton();
        bo38 = new javax.swing.JButton();
        bo39 = new javax.swing.JButton();
        bo40 = new javax.swing.JButton();
        bo41 = new javax.swing.JButton();
        bo42 = new javax.swing.JButton();
        bo43 = new javax.swing.JButton();
        bo44 = new javax.swing.JButton();
        bo45 = new javax.swing.JButton();
        bo46 = new javax.swing.JButton();
        bo47 = new javax.swing.JButton();
        bo48 = new javax.swing.JButton();
        bo49 = new javax.swing.JButton();
        bo50 = new javax.swing.JButton();
        bo51 = new javax.swing.JButton();
        bo52 = new javax.swing.JButton();
        bo53 = new javax.swing.JButton();
        bo54 = new javax.swing.JButton();
        bo55 = new javax.swing.JButton();
        bo56 = new javax.swing.JButton();
        bo57 = new javax.swing.JButton();
        bo58 = new javax.swing.JButton();
        bo59 = new javax.swing.JButton();
        bo60 = new javax.swing.JButton();
        bo61 = new javax.swing.JButton();
        bo62 = new javax.swing.JButton();
        bo63 = new javax.swing.JButton();
        bo64 = new javax.swing.JButton();
        bo65 = new javax.swing.JButton();
        bo66 = new javax.swing.JButton();
        bo67 = new javax.swing.JButton();
        bo68 = new javax.swing.JButton();
        bo69 = new javax.swing.JButton();
        bo70 = new javax.swing.JButton();
        bo71 = new javax.swing.JButton();
        bo72 = new javax.swing.JButton();
        bo73 = new javax.swing.JButton();
        bo74 = new javax.swing.JButton();
        bo75 = new javax.swing.JButton();
        bo76 = new javax.swing.JButton();
        bo77 = new javax.swing.JButton();
        bo78 = new javax.swing.JButton();
        bo79 = new javax.swing.JButton();
        bo80 = new javax.swing.JButton();
        bo81 = new javax.swing.JButton();
        bo82 = new javax.swing.JButton();
        bo83 = new javax.swing.JButton();
        bo84 = new javax.swing.JButton();
        bo85 = new javax.swing.JButton();
        bo86 = new javax.swing.JButton();
        bo87 = new javax.swing.JButton();
        bo88 = new javax.swing.JButton();
        bo89 = new javax.swing.JButton();
        bo90 = new javax.swing.JButton();
        bo91 = new javax.swing.JButton();
        bo92 = new javax.swing.JButton();
        bo93 = new javax.swing.JButton();
        bo94 = new javax.swing.JButton();
        bo95 = new javax.swing.JButton();
        bo96 = new javax.swing.JButton();
        bo97 = new javax.swing.JButton();
        bo98 = new javax.swing.JButton();
        bo99 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.LINE_AXIS));

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 204), 5));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("BATALLA NAVAL");

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(0, 153, 153)));
        jPanel3.setForeground(new java.awt.Color(0, 153, 255));
        jPanel3.setLayout(new java.awt.GridLayout(10, 10));

        bo00.setBackground(new java.awt.Color(0, 0, 255));
        bo00.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bo00ActionPerformed(evt);
            }
        });
        jPanel3.add(bo00);

        bo01.setBackground(new java.awt.Color(0, 0, 255));
        bo01.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bo01ActionPerformed(evt);
            }
        });
        jPanel3.add(bo01);

        bo02.setBackground(new java.awt.Color(0, 0, 255));
        bo02.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bo02ActionPerformed(evt);
            }
        });
        jPanel3.add(bo02);

        bo03.setBackground(new java.awt.Color(0, 0, 255));
        bo03.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bo03ActionPerformed(evt);
            }
        });
        jPanel3.add(bo03);

        bo04.setBackground(new java.awt.Color(0, 0, 255));
        bo04.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bo04ActionPerformed(evt);
            }
        });
        jPanel3.add(bo04);

        bo05.setBackground(new java.awt.Color(0, 0, 255));
        bo05.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bo05ActionPerformed(evt);
            }
        });
        jPanel3.add(bo05);

        bo06.setBackground(new java.awt.Color(0, 0, 255));
        bo06.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bo06ActionPerformed(evt);
            }
        });
        jPanel3.add(bo06);

        bo07.setBackground(new java.awt.Color(0, 0, 255));
        bo07.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bo07ActionPerformed(evt);
            }
        });
        jPanel3.add(bo07);

        bo08.setBackground(new java.awt.Color(0, 0, 255));
        bo08.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bo08ActionPerformed(evt);
            }
        });
        jPanel3.add(bo08);

        bo09.setBackground(new java.awt.Color(0, 0, 255));
        bo09.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bo09ActionPerformed(evt);
            }
        });
        jPanel3.add(bo09);

        bo10.setBackground(new java.awt.Color(0, 0, 255));
        bo10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bo10ActionPerformed(evt);
            }
        });
        jPanel3.add(bo10);

        bo11.setBackground(new java.awt.Color(0, 0, 255));
        bo11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bo11ActionPerformed(evt);
            }
        });
        jPanel3.add(bo11);

        bo12.setBackground(new java.awt.Color(0, 0, 255));
        bo12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bo12ActionPerformed(evt);
            }
        });
        jPanel3.add(bo12);

        bo13.setBackground(new java.awt.Color(0, 0, 255));
        bo13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bo13ActionPerformed(evt);
            }
        });
        jPanel3.add(bo13);

        bo14.setBackground(new java.awt.Color(0, 0, 255));
        bo14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bo14ActionPerformed(evt);
            }
        });
        jPanel3.add(bo14);

        bo15.setBackground(new java.awt.Color(0, 0, 255));
        bo15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bo15ActionPerformed(evt);
            }
        });
        jPanel3.add(bo15);

        bo16.setBackground(new java.awt.Color(0, 0, 255));
        bo16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bo16ActionPerformed(evt);
            }
        });
        jPanel3.add(bo16);

        bo17.setBackground(new java.awt.Color(0, 0, 255));
        bo17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bo17ActionPerformed(evt);
            }
        });
        jPanel3.add(bo17);

        bo18.setBackground(new java.awt.Color(0, 0, 255));
        bo18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bo18ActionPerformed(evt);
            }
        });
        jPanel3.add(bo18);

        bo19.setBackground(new java.awt.Color(0, 0, 255));
        bo19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bo19ActionPerformed(evt);
            }
        });
        jPanel3.add(bo19);

        bo20.setBackground(new java.awt.Color(0, 0, 255));
        bo20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bo20ActionPerformed(evt);
            }
        });
        jPanel3.add(bo20);

        bo21.setBackground(new java.awt.Color(0, 0, 255));
        bo21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bo21ActionPerformed(evt);
            }
        });
        jPanel3.add(bo21);

        bo22.setBackground(new java.awt.Color(0, 0, 255));
        bo22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bo22ActionPerformed(evt);
            }
        });
        jPanel3.add(bo22);

        bo23.setBackground(new java.awt.Color(0, 0, 255));
        bo23.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bo23ActionPerformed(evt);
            }
        });
        jPanel3.add(bo23);

        bo24.setBackground(new java.awt.Color(0, 0, 255));
        bo24.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bo24ActionPerformed(evt);
            }
        });
        jPanel3.add(bo24);

        bo25.setBackground(new java.awt.Color(0, 0, 255));
        bo25.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bo25ActionPerformed(evt);
            }
        });
        jPanel3.add(bo25);

        bo26.setBackground(new java.awt.Color(0, 0, 255));
        bo26.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bo26ActionPerformed(evt);
            }
        });
        jPanel3.add(bo26);

        bo27.setBackground(new java.awt.Color(0, 0, 255));
        bo27.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bo27ActionPerformed(evt);
            }
        });
        jPanel3.add(bo27);

        bo28.setBackground(new java.awt.Color(0, 0, 255));
        bo28.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bo28ActionPerformed(evt);
            }
        });
        jPanel3.add(bo28);

        bo29.setBackground(new java.awt.Color(0, 0, 255));
        bo29.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bo29ActionPerformed(evt);
            }
        });
        jPanel3.add(bo29);

        bo30.setBackground(new java.awt.Color(0, 0, 255));
        bo30.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bo30ActionPerformed(evt);
            }
        });
        jPanel3.add(bo30);

        bo31.setBackground(new java.awt.Color(0, 0, 255));
        bo31.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bo31ActionPerformed(evt);
            }
        });
        jPanel3.add(bo31);

        bo32.setBackground(new java.awt.Color(0, 0, 255));
        bo32.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bo32ActionPerformed(evt);
            }
        });
        jPanel3.add(bo32);

        bo33.setBackground(new java.awt.Color(0, 0, 255));
        bo33.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bo33ActionPerformed(evt);
            }
        });
        jPanel3.add(bo33);

        bo34.setBackground(new java.awt.Color(0, 0, 255));
        bo34.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bo34ActionPerformed(evt);
            }
        });
        jPanel3.add(bo34);

        bo35.setBackground(new java.awt.Color(0, 0, 255));
        bo35.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bo35ActionPerformed(evt);
            }
        });
        jPanel3.add(bo35);

        bo36.setBackground(new java.awt.Color(0, 0, 255));
        bo36.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bo36ActionPerformed(evt);
            }
        });
        jPanel3.add(bo36);

        bo37.setBackground(new java.awt.Color(0, 0, 255));
        bo37.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bo37ActionPerformed(evt);
            }
        });
        jPanel3.add(bo37);

        bo38.setBackground(new java.awt.Color(0, 0, 255));
        bo38.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bo38ActionPerformed(evt);
            }
        });
        jPanel3.add(bo38);

        bo39.setBackground(new java.awt.Color(0, 0, 255));
        bo39.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bo39ActionPerformed(evt);
            }
        });
        jPanel3.add(bo39);

        bo40.setBackground(new java.awt.Color(0, 0, 255));
        bo40.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bo40ActionPerformed(evt);
            }
        });
        jPanel3.add(bo40);

        bo41.setBackground(new java.awt.Color(0, 0, 255));
        bo41.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bo41ActionPerformed(evt);
            }
        });
        jPanel3.add(bo41);

        bo42.setBackground(new java.awt.Color(0, 0, 255));
        bo42.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bo42ActionPerformed(evt);
            }
        });
        jPanel3.add(bo42);

        bo43.setBackground(new java.awt.Color(0, 0, 255));
        bo43.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bo43ActionPerformed(evt);
            }
        });
        jPanel3.add(bo43);

        bo44.setBackground(new java.awt.Color(0, 0, 255));
        bo44.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bo44ActionPerformed(evt);
            }
        });
        jPanel3.add(bo44);

        bo45.setBackground(new java.awt.Color(0, 0, 255));
        bo45.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bo45ActionPerformed(evt);
            }
        });
        jPanel3.add(bo45);

        bo46.setBackground(new java.awt.Color(0, 0, 255));
        bo46.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bo46ActionPerformed(evt);
            }
        });
        jPanel3.add(bo46);

        bo47.setBackground(new java.awt.Color(0, 0, 255));
        bo47.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bo47ActionPerformed(evt);
            }
        });
        jPanel3.add(bo47);

        bo48.setBackground(new java.awt.Color(0, 0, 255));
        bo48.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bo48ActionPerformed(evt);
            }
        });
        jPanel3.add(bo48);

        bo49.setBackground(new java.awt.Color(0, 0, 255));
        bo49.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bo49ActionPerformed(evt);
            }
        });
        jPanel3.add(bo49);

        bo50.setBackground(new java.awt.Color(0, 0, 255));
        bo50.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bo50ActionPerformed(evt);
            }
        });
        jPanel3.add(bo50);

        bo51.setBackground(new java.awt.Color(0, 0, 255));
        bo51.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bo51ActionPerformed(evt);
            }
        });
        jPanel3.add(bo51);

        bo52.setBackground(new java.awt.Color(0, 0, 255));
        bo52.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bo52ActionPerformed(evt);
            }
        });
        jPanel3.add(bo52);

        bo53.setBackground(new java.awt.Color(0, 0, 255));
        bo53.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bo53ActionPerformed(evt);
            }
        });
        jPanel3.add(bo53);

        bo54.setBackground(new java.awt.Color(0, 0, 255));
        bo54.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bo54ActionPerformed(evt);
            }
        });
        jPanel3.add(bo54);

        bo55.setBackground(new java.awt.Color(0, 0, 255));
        bo55.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bo55ActionPerformed(evt);
            }
        });
        jPanel3.add(bo55);

        bo56.setBackground(new java.awt.Color(0, 0, 255));
        bo56.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bo56ActionPerformed(evt);
            }
        });
        jPanel3.add(bo56);

        bo57.setBackground(new java.awt.Color(0, 0, 255));
        bo57.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bo57ActionPerformed(evt);
            }
        });
        jPanel3.add(bo57);

        bo58.setBackground(new java.awt.Color(0, 0, 255));
        bo58.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bo58ActionPerformed(evt);
            }
        });
        jPanel3.add(bo58);

        bo59.setBackground(new java.awt.Color(0, 0, 255));
        bo59.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bo59ActionPerformed(evt);
            }
        });
        jPanel3.add(bo59);

        bo60.setBackground(new java.awt.Color(0, 0, 255));
        bo60.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bo60ActionPerformed(evt);
            }
        });
        jPanel3.add(bo60);

        bo61.setBackground(new java.awt.Color(0, 0, 255));
        bo61.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bo61ActionPerformed(evt);
            }
        });
        jPanel3.add(bo61);

        bo62.setBackground(new java.awt.Color(0, 0, 255));
        bo62.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bo62ActionPerformed(evt);
            }
        });
        jPanel3.add(bo62);

        bo63.setBackground(new java.awt.Color(0, 0, 255));
        bo63.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bo63ActionPerformed(evt);
            }
        });
        jPanel3.add(bo63);

        bo64.setBackground(new java.awt.Color(0, 0, 255));
        bo64.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bo64ActionPerformed(evt);
            }
        });
        jPanel3.add(bo64);

        bo65.setBackground(new java.awt.Color(0, 0, 255));
        bo65.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bo65ActionPerformed(evt);
            }
        });
        jPanel3.add(bo65);

        bo66.setBackground(new java.awt.Color(0, 0, 255));
        bo66.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bo66ActionPerformed(evt);
            }
        });
        jPanel3.add(bo66);

        bo67.setBackground(new java.awt.Color(0, 0, 255));
        bo67.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bo67ActionPerformed(evt);
            }
        });
        jPanel3.add(bo67);

        bo68.setBackground(new java.awt.Color(0, 0, 255));
        bo68.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bo68ActionPerformed(evt);
            }
        });
        jPanel3.add(bo68);

        bo69.setBackground(new java.awt.Color(0, 0, 255));
        bo69.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bo69ActionPerformed(evt);
            }
        });
        jPanel3.add(bo69);

        bo70.setBackground(new java.awt.Color(0, 0, 255));
        bo70.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bo70ActionPerformed(evt);
            }
        });
        jPanel3.add(bo70);

        bo71.setBackground(new java.awt.Color(0, 0, 255));
        bo71.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bo71ActionPerformed(evt);
            }
        });
        jPanel3.add(bo71);

        bo72.setBackground(new java.awt.Color(0, 0, 255));
        bo72.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bo72ActionPerformed(evt);
            }
        });
        jPanel3.add(bo72);

        bo73.setBackground(new java.awt.Color(0, 0, 255));
        bo73.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bo73ActionPerformed(evt);
            }
        });
        jPanel3.add(bo73);

        bo74.setBackground(new java.awt.Color(0, 0, 255));
        bo74.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bo74ActionPerformed(evt);
            }
        });
        jPanel3.add(bo74);

        bo75.setBackground(new java.awt.Color(0, 0, 255));
        bo75.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bo75ActionPerformed(evt);
            }
        });
        jPanel3.add(bo75);

        bo76.setBackground(new java.awt.Color(0, 0, 255));
        bo76.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bo76ActionPerformed(evt);
            }
        });
        jPanel3.add(bo76);

        bo77.setBackground(new java.awt.Color(0, 0, 255));
        bo77.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bo77ActionPerformed(evt);
            }
        });
        jPanel3.add(bo77);

        bo78.setBackground(new java.awt.Color(0, 0, 255));
        bo78.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bo78ActionPerformed(evt);
            }
        });
        jPanel3.add(bo78);

        bo79.setBackground(new java.awt.Color(0, 0, 255));
        bo79.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bo79ActionPerformed(evt);
            }
        });
        jPanel3.add(bo79);

        bo80.setBackground(new java.awt.Color(0, 0, 255));
        bo80.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bo80ActionPerformed(evt);
            }
        });
        jPanel3.add(bo80);

        bo81.setBackground(new java.awt.Color(0, 0, 255));
        bo81.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bo81ActionPerformed(evt);
            }
        });
        jPanel3.add(bo81);

        bo82.setBackground(new java.awt.Color(0, 0, 255));
        bo82.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bo82ActionPerformed(evt);
            }
        });
        jPanel3.add(bo82);

        bo83.setBackground(new java.awt.Color(0, 0, 255));
        bo83.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bo83ActionPerformed(evt);
            }
        });
        jPanel3.add(bo83);

        bo84.setBackground(new java.awt.Color(0, 0, 255));
        bo84.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bo84ActionPerformed(evt);
            }
        });
        jPanel3.add(bo84);

        bo85.setBackground(new java.awt.Color(0, 0, 255));
        bo85.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bo85ActionPerformed(evt);
            }
        });
        jPanel3.add(bo85);

        bo86.setBackground(new java.awt.Color(0, 0, 255));
        bo86.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bo86ActionPerformed(evt);
            }
        });
        jPanel3.add(bo86);

        bo87.setBackground(new java.awt.Color(0, 0, 255));
        bo87.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bo87ActionPerformed(evt);
            }
        });
        jPanel3.add(bo87);

        bo88.setBackground(new java.awt.Color(0, 0, 255));
        bo88.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bo88ActionPerformed(evt);
            }
        });
        jPanel3.add(bo88);

        bo89.setBackground(new java.awt.Color(0, 0, 255));
        bo89.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bo89ActionPerformed(evt);
            }
        });
        jPanel3.add(bo89);

        bo90.setBackground(new java.awt.Color(0, 0, 255));
        bo90.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bo90ActionPerformed(evt);
            }
        });
        jPanel3.add(bo90);

        bo91.setBackground(new java.awt.Color(0, 0, 255));
        bo91.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bo91ActionPerformed(evt);
            }
        });
        jPanel3.add(bo91);

        bo92.setBackground(new java.awt.Color(0, 0, 255));
        bo92.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bo92ActionPerformed(evt);
            }
        });
        jPanel3.add(bo92);

        bo93.setBackground(new java.awt.Color(0, 0, 255));
        bo93.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bo93ActionPerformed(evt);
            }
        });
        jPanel3.add(bo93);

        bo94.setBackground(new java.awt.Color(0, 0, 255));
        bo94.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bo94ActionPerformed(evt);
            }
        });
        jPanel3.add(bo94);

        bo95.setBackground(new java.awt.Color(0, 0, 255));
        bo95.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bo95ActionPerformed(evt);
            }
        });
        jPanel3.add(bo95);

        bo96.setBackground(new java.awt.Color(0, 0, 255));
        bo96.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bo96ActionPerformed(evt);
            }
        });
        jPanel3.add(bo96);

        bo97.setBackground(new java.awt.Color(0, 0, 255));
        bo97.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bo97ActionPerformed(evt);
            }
        });
        jPanel3.add(bo97);

        bo98.setBackground(new java.awt.Color(0, 0, 255));
        bo98.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bo98ActionPerformed(evt);
            }
        });
        jPanel3.add(bo98);

        bo99.setBackground(new java.awt.Color(0, 0, 255));
        bo99.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bo99ActionPerformed(evt);
            }
        });
        jPanel3.add(bo99);

        jLabel2.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 36)); // NOI18N
        jLabel2.setText("derribados");

        jLabel3.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 36)); // NOI18N
        jLabel3.setText("cantidad de misiles");

        jLabel4.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 36)); // NOI18N
        jLabel4.setText("disparos");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(61, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(273, 273, 273))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 825, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(101, 101, 101)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(86, 86, 86)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 324, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3)
                        .addContainerGap(64, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel4)
                        .addGap(26, 26, 26))))
        );

        getContentPane().add(jPanel1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bo00ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bo00ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bo00ActionPerformed

    private void bo01ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bo01ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bo01ActionPerformed

    private void bo02ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bo02ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bo02ActionPerformed

    private void bo03ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bo03ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bo03ActionPerformed

    private void bo04ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bo04ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bo04ActionPerformed

    private void bo05ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bo05ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bo05ActionPerformed

    private void bo06ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bo06ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bo06ActionPerformed

    private void bo07ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bo07ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bo07ActionPerformed

    private void bo08ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bo08ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bo08ActionPerformed

    private void bo09ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bo09ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bo09ActionPerformed

    private void bo10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bo10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bo10ActionPerformed

    private void bo11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bo11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bo11ActionPerformed

    private void bo12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bo12ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bo12ActionPerformed

    private void bo13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bo13ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bo13ActionPerformed

    private void bo14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bo14ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bo14ActionPerformed

    private void bo15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bo15ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bo15ActionPerformed

    private void bo16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bo16ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bo16ActionPerformed

    private void bo17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bo17ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bo17ActionPerformed

    private void bo18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bo18ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bo18ActionPerformed

    private void bo19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bo19ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bo19ActionPerformed

    private void bo20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bo20ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bo20ActionPerformed

    private void bo21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bo21ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bo21ActionPerformed

    private void bo22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bo22ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bo22ActionPerformed

    private void bo23ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bo23ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bo23ActionPerformed

    private void bo24ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bo24ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bo24ActionPerformed

    private void bo25ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bo25ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bo25ActionPerformed

    private void bo26ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bo26ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bo26ActionPerformed

    private void bo27ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bo27ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bo27ActionPerformed

    private void bo28ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bo28ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bo28ActionPerformed

    private void bo29ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bo29ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bo29ActionPerformed

    private void bo30ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bo30ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bo30ActionPerformed

    private void bo31ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bo31ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bo31ActionPerformed

    private void bo32ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bo32ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bo32ActionPerformed

    private void bo33ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bo33ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bo33ActionPerformed

    private void bo34ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bo34ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bo34ActionPerformed

    private void bo35ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bo35ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bo35ActionPerformed

    private void bo36ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bo36ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bo36ActionPerformed

    private void bo37ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bo37ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bo37ActionPerformed

    private void bo38ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bo38ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bo38ActionPerformed

    private void bo39ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bo39ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bo39ActionPerformed

    private void bo40ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bo40ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bo40ActionPerformed

    private void bo41ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bo41ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bo41ActionPerformed

    private void bo42ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bo42ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bo42ActionPerformed

    private void bo43ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bo43ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bo43ActionPerformed

    private void bo44ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bo44ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bo44ActionPerformed

    private void bo45ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bo45ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bo45ActionPerformed

    private void bo46ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bo46ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bo46ActionPerformed

    private void bo47ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bo47ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bo47ActionPerformed

    private void bo48ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bo48ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bo48ActionPerformed

    private void bo49ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bo49ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bo49ActionPerformed

    private void bo50ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bo50ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bo50ActionPerformed

    private void bo51ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bo51ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bo51ActionPerformed

    private void bo52ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bo52ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bo52ActionPerformed

    private void bo53ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bo53ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bo53ActionPerformed

    private void bo54ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bo54ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bo54ActionPerformed

    private void bo55ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bo55ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bo55ActionPerformed

    private void bo56ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bo56ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bo56ActionPerformed

    private void bo57ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bo57ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bo57ActionPerformed

    private void bo58ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bo58ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bo58ActionPerformed

    private void bo59ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bo59ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bo59ActionPerformed

    private void bo60ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bo60ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bo60ActionPerformed

    private void bo61ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bo61ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bo61ActionPerformed

    private void bo62ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bo62ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bo62ActionPerformed

    private void bo63ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bo63ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bo63ActionPerformed

    private void bo64ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bo64ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bo64ActionPerformed

    private void bo65ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bo65ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bo65ActionPerformed

    private void bo66ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bo66ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bo66ActionPerformed

    private void bo67ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bo67ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bo67ActionPerformed

    private void bo68ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bo68ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bo68ActionPerformed

    private void bo69ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bo69ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bo69ActionPerformed

    private void bo70ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bo70ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bo70ActionPerformed

    private void bo71ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bo71ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bo71ActionPerformed

    private void bo72ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bo72ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bo72ActionPerformed

    private void bo73ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bo73ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bo73ActionPerformed

    private void bo74ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bo74ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bo74ActionPerformed

    private void bo75ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bo75ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bo75ActionPerformed

    private void bo76ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bo76ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bo76ActionPerformed

    private void bo77ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bo77ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bo77ActionPerformed

    private void bo78ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bo78ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bo78ActionPerformed

    private void bo79ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bo79ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bo79ActionPerformed

    private void bo80ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bo80ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bo80ActionPerformed

    private void bo81ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bo81ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bo81ActionPerformed

    private void bo82ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bo82ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bo82ActionPerformed

    private void bo83ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bo83ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bo83ActionPerformed

    private void bo84ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bo84ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bo84ActionPerformed

    private void bo85ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bo85ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bo85ActionPerformed

    private void bo86ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bo86ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bo86ActionPerformed

    private void bo87ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bo87ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bo87ActionPerformed

    private void bo88ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bo88ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bo88ActionPerformed

    private void bo89ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bo89ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bo89ActionPerformed

    private void bo90ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bo90ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bo90ActionPerformed

    private void bo91ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bo91ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bo91ActionPerformed

    private void bo92ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bo92ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bo92ActionPerformed

    private void bo93ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bo93ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bo93ActionPerformed

    private void bo94ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bo94ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bo94ActionPerformed

    private void bo95ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bo95ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bo95ActionPerformed

    private void bo96ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bo96ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bo96ActionPerformed

    private void bo97ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bo97ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bo97ActionPerformed

    private void bo98ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bo98ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bo98ActionPerformed

    private void bo99ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bo99ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bo99ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ejemplo.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ejemplo.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ejemplo.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ejemplo.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ejemplo().setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bo00;
    private javax.swing.JButton bo01;
    private javax.swing.JButton bo02;
    private javax.swing.JButton bo03;
    private javax.swing.JButton bo04;
    private javax.swing.JButton bo05;
    private javax.swing.JButton bo06;
    private javax.swing.JButton bo07;
    private javax.swing.JButton bo08;
    private javax.swing.JButton bo09;
    private javax.swing.JButton bo10;
    private javax.swing.JButton bo11;
    private javax.swing.JButton bo12;
    private javax.swing.JButton bo13;
    private javax.swing.JButton bo14;
    private javax.swing.JButton bo15;
    private javax.swing.JButton bo16;
    private javax.swing.JButton bo17;
    private javax.swing.JButton bo18;
    private javax.swing.JButton bo19;
    private javax.swing.JButton bo20;
    private javax.swing.JButton bo21;
    private javax.swing.JButton bo22;
    private javax.swing.JButton bo23;
    private javax.swing.JButton bo24;
    private javax.swing.JButton bo25;
    private javax.swing.JButton bo26;
    private javax.swing.JButton bo27;
    private javax.swing.JButton bo28;
    private javax.swing.JButton bo29;
    private javax.swing.JButton bo30;
    private javax.swing.JButton bo31;
    private javax.swing.JButton bo32;
    private javax.swing.JButton bo33;
    private javax.swing.JButton bo34;
    private javax.swing.JButton bo35;
    private javax.swing.JButton bo36;
    private javax.swing.JButton bo37;
    private javax.swing.JButton bo38;
    private javax.swing.JButton bo39;
    private javax.swing.JButton bo40;
    private javax.swing.JButton bo41;
    private javax.swing.JButton bo42;
    private javax.swing.JButton bo43;
    private javax.swing.JButton bo44;
    private javax.swing.JButton bo45;
    private javax.swing.JButton bo46;
    private javax.swing.JButton bo47;
    private javax.swing.JButton bo48;
    private javax.swing.JButton bo49;
    private javax.swing.JButton bo50;
    private javax.swing.JButton bo51;
    private javax.swing.JButton bo52;
    private javax.swing.JButton bo53;
    private javax.swing.JButton bo54;
    private javax.swing.JButton bo55;
    private javax.swing.JButton bo56;
    private javax.swing.JButton bo57;
    private javax.swing.JButton bo58;
    private javax.swing.JButton bo59;
    private javax.swing.JButton bo60;
    private javax.swing.JButton bo61;
    private javax.swing.JButton bo62;
    private javax.swing.JButton bo63;
    private javax.swing.JButton bo64;
    private javax.swing.JButton bo65;
    private javax.swing.JButton bo66;
    private javax.swing.JButton bo67;
    private javax.swing.JButton bo68;
    private javax.swing.JButton bo69;
    private javax.swing.JButton bo70;
    private javax.swing.JButton bo71;
    private javax.swing.JButton bo72;
    private javax.swing.JButton bo73;
    private javax.swing.JButton bo74;
    private javax.swing.JButton bo75;
    private javax.swing.JButton bo76;
    private javax.swing.JButton bo77;
    private javax.swing.JButton bo78;
    private javax.swing.JButton bo79;
    private javax.swing.JButton bo80;
    private javax.swing.JButton bo81;
    private javax.swing.JButton bo82;
    private javax.swing.JButton bo83;
    private javax.swing.JButton bo84;
    private javax.swing.JButton bo85;
    private javax.swing.JButton bo86;
    private javax.swing.JButton bo87;
    private javax.swing.JButton bo88;
    private javax.swing.JButton bo89;
    private javax.swing.JButton bo90;
    private javax.swing.JButton bo91;
    private javax.swing.JButton bo92;
    private javax.swing.JButton bo93;
    private javax.swing.JButton bo94;
    private javax.swing.JButton bo95;
    private javax.swing.JButton bo96;
    private javax.swing.JButton bo97;
    private javax.swing.JButton bo98;
    private javax.swing.JButton bo99;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    // End of variables declaration//GEN-END:variables

}
